### ISSUE TITLE
Show a progress bar when re-indexing vault in Obsidian

### ISSUE THREAD

**Issue by abhuva** [debanjum/khoj#129]
Currently there is no indication what the software is doing, any aproximate time, if its stuck or not...
Please add some kind of progress bar, so its better visible what is going on.

**Comment by debanjum** [comment]
Added indicator to show indexing is actively in progress. @abhuva (or others), feel free to reopen this issue if the fix is unsatisfactory. The changes will be visible in the khoj obsidian plugin once a new release is published. Hopefully by the end of this week.

https://user-images.githubusercontent.com/6413477/218625109-f0a94175-97c7-478f-8926-437d1731077b.mov
