### ISSUE TITLE
Upon initial installation in Obsidian: Error if (t == SearchType.Markdown or t == None) and config.content_type.markdown: AttributeError: 'NoneType' object has no attribute 'content_type'

### ISSUE THREAD

**Issue by tleers** [debanjum/khoj#136]
Following the obsidian README, including installing the community plugin as well as running khoj-assistant back-end, led to the following error:

```python 
if (t == SearchType.Markdown or t == None) and config.content_type.markdown:
  AttributeError: 'NoneType' object has no attribute 'content_type'
```

Solved by restarting obsidian markdown session after having installed the plugin.

**Comment by debanjum** [comment]
Hi @tleers, thanks for reporting this issue!

Did you install the khoj obsidian community plugin before starting the `khoj-assistant` backend?

I think that would both trigger the issue you saw and have it resolve on restarting obsidian. 
This is because the plugin configures the khoj backend when either 1. the plugin is installed or 2. obsidian is started.
If the plugin is installed before the khoj backend is configured, it wouldn't be able to configure the backend. I'd expect doing a search in that scenario to trigger the above error you saw

**Comment by debanjum** [comment]
Hey @tleers,
I've updated [the setup instructions](https://github.com/debanjum/khoj/tree/master/src/interface/obsidian#Setup) to mention following the installation steps in order. 
Closing this issue for now as I don't have any other actionable items to follow-up on this issue. 
Of course feel free to provide more information to get this issue reopened if you feel it necessary.
