### ISSUE TITLE
Null Reference Error on starting Khoj with GUI on First Run

### ISSUE THREAD

**Issue by CrackheadoooObsidianUserooo** [debanjum/khoj#167]
![KHOJ bug](https://user-images.githubusercontent.com/121588624/220403560-8feef3b6-2edb-4587-94db-4abe6bd08634.png)

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by debanjum** [comment]
It's unfortunate  that Khoj doesn't start for you after first run. I'll need a little more information to debug the issue: 
1. Did you install/reload the Khoj obsidian plugin after you started Khoj the first time? 
2. Did search using Khoj (from Obsidian or otherwise) work for you at any point?

If not,
1. Can you delete your `khoj` directory at `C:\Users\<your-windows-username>\.khoj`, start khoj again with `khoj --no-gui -vv` and share what the khoj logs show?
2. Also can you share the version of khoj you are using by running `khoj -V` or `pip install khoj-assistant` in your Command Prompt?

**Comment by thomclae33** [comment]
I had the same issue, but was able to get things working again without the gui. Works like a charm  🙌
