### ISSUE TITLE
Plans for indexing other file types?

### ISSUE THREAD

**Issue by thomclae33** [debanjum/khoj#170]
Just a curious question: are there any plans to also index other file types, such as PDF or EPUB?

**Comment by debanjum** [comment]
Yup, being able to index all the private content folks want to search over is really important for Khoj to be useful.
But developing and maintaining that just by myself may become untenable soon. 
Which is why I'm working on supporting external content plugins in Khoj. I've created an issue to track that in #171
Let me know if that answers your question?

**Comment by thomclae33** [comment]
That answered it perfectly. Thank you! Great vision
