### ISSUE TITLE
The chat is working.. :) but it is not very useful ... or relevant or learning. How to correct/improve that?

### ISSUE THREAD

**Issue by jasmeetchadha** [debanjum/khoj#180]
Thanks Deb (looking forward to speaking on twitter... I cant sent you direct messages there)

![image](https://user-images.githubusercontent.com/49923268/222707297-bc8807bb-17a9-4ec6-8e09-fe36be16bcd6.png)

**Comment by debanjum** [comment]
Thanks for sharing a snippet of your chat logs! And yeah, they do not seem useful at all. 

Set the chat type to `summarize` (instead of the default `chat` type) to stop the model from making up random stuff. You can do that by opening https://127.0.0.1:8000/chat?t=summarize or by selecting it in the dropdown on the bottom right of the chat webpage. Let me know if that helps?

Otherwise I'm working on a few improvements to the chat feature that should roll out in 1-2 weeks.

**Comment by debanjum** [comment]
> looking forward to speaking on twitter... I cant sent you direct messages there

Ah fixed that. You should be able to message me now

**Comment by jasmeetchadha** [comment]
Thanks, its set to summarize. 

Looking forward to improvements!
