### ISSUE TITLE
Do not fail if user provides config for a search type but does not have data

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#23]
Currently, the initialize_search method will end up failing if user has specified attributes in the config for a search type but does not have data present for it in the designated location. Do not fail when this happens. Rather, warn. ﻿

**Comment by debanjum** [comment]
Do not remember the complete context for this issue. But if the input files/filter/directory has no data, we should fail with a clear, actionable error message IMO
- The issue of failing with an unclear error message on empty file was fixed in 372dcd2dbc8871833cb11fc53ada033064cb673d
- We already fail with a FileNotFoundError if the specified input file in config does not exist
This seems good enough for now. So closing this issue. FYI @sabaimran
