### ISSUE TITLE
Investigate simplenote support

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#51]
- [simplenote](https://simplenote.com/) is a note-taking app that supports generic .txt files as well as markdown .md files. See if there's anything in particular required for using this.

Longer term:
- See if there's a way to give deeper search support for Simplenote, perhaps in application? The code is [open source](https://simplenote.com/developers/). Could we add a Khoj extension?

**Comment by debanjum** [comment]
Indexing markdown files (from SimpleNote or otherwise) and searching over them using the Khoj Web UI has been possible for a while.
But it would not be possible to use Khoj from within the SimpleNote app as SimpleNote does not currently support third party plugins and it's API is deprecated[^1]

Feel free to reopen this issue in case any new developments or action items emerge

[^1]: https://simplenote.com/developers/#:~:text=Third%20Party%20Applications
