### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by maltegrosse** [debanjum/khoj#98]
Hi, I assume only English language is support so far.
Is it possible to extend it?

**Comment by debanjum** [comment]
Which language(s) are you looking to search on?

The default models only work with English. But you can configure Khoj to use [multi-lingual sentence-transformer models](https://www.sbert.net/docs/pretrained_models.html#multi-lingual-models) for search too. Try the [paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) model to see if it works fine for your preferred language(s). It supports [50+ languages](https://www.sbert.net/docs/pretrained_models.html#:~:text=we%20used%20the%20following%2050%2B%20languages) and has good search quality and speed.

You'll need to manually update `search-type > asymmetric > encoder` to `sentence-transformer/paraphrase-multilingual-MiniLM-L12-v2` in your `~/.khoj/khoj.yml` file for now. See diff of `khoj.yml` below for illustration:
<img width="536" alt="Update encoder to use multilingual model in Khoj yml " src="https://user-images.githubusercontent.com/6413477/190221234-fc57ac5d-0b24-4322-b586-59b27f48bbb6.png">

**Comment by maltegrosse** [comment]
Thank you - I will try out.

**Comment by panomitrius** [comment]
Doesn't download when I change this as suggested:

```
Repository Not Found for url: https://huggingface.co/api/models/sentence-transformer/paraphrase-multilingual-MiniLM-L12-v2.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

I downloaded it manually from [the link posted above](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) and put it in 

`~/.khoj/search/asymmetric/sentence-transformer_paraphrase-multilingual-MiniLM-L12-v2`

Seems to work, but then running http://127.0.0.1:8000/regenerate doesn't work and gives error output:
`detail	"Not Found"`

**Comment by debanjum** [comment]
> It doesn't download automatically when I change the config as you suggested:

@panomitrius, thanks for notifying about this. Can verify that the previous suggested config update doesn't work. 

`~/.khoj/khoj.yml` needs to be updated to use `paraphrase-multilingual-MiniLM-L12-v2` as the asymmetric encoder instead of `sentence_transformer/paraphrase-multilingual-MiniLM-L12-v2`. 
I've just updated the Readme to reflect that in commit a9b8197

>  then running http://127.0.0.1:8000/regenerate doesn't work and gives error output:
`detail	"Not Found"`

Yeah, the API got updated since my previous post. You can (force) update the index by either running `khoj --regenerate` like you did or open http://127.0.0.1:8000/update?force=true. See [the Readme](https://github.com/debanjum/khoj#search-across-different-languages) for details
